### ISSUE TITLE
InApp Message not showing

### ISSUE THREAD

**Issue by jkblgithub** [firebase/firebase-android-sdk#1203]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component:InAppMessaging
  * Component version:
implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-inappmessaging-display:19.0.3'

### [REQUIRED] Step 3: Describe the problem
Test message not shown on device as described in your docs:
https://firebase.google.com/docs/in-app-messaging/get-started?authuser=0&platform=android

#### Steps to reproduce:
1. Configure InApp messaging as per docs
2. Try to send a test message as per docs
3. No message shown - log output:

Setting display event listener
went foreground
Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
Recoverable exception while reading cache: /data/user/0/***/files/fiam_impressions_store_file (No such file or directory)
Fetching campaigns from service.
Service fetch error: INVALID_ARGUMENT: Request contains an invalid argument.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @jkblgithub currently, there’s no reported issues on our end. Also, I’ve tried sending a Firebase In-App Messaging (FIAM) campaign, and I’m not experiencing this issue.

I'd suggest you try out the quickstart for Android, as that should be working fine. Once you get the quickstart working, you can use it as a reference and compare with your project to see where issues occur. 

If you are able to reproduce the same error with the quickstart, please feel free to comment back, and we can take a look further into this issue.

**Comment by jkblgithub** [comment]
I was working from the quickstart and if you look at the code I provided it should show you that in-app messaging was installed. I tested again today and get the same error:
Service fetch error: INVALID_ARGUMENT: Request contains an invalid argument.

**Comment by aguatno** [comment]
Could you try re-downloading the google-services.json file?

**Comment by mtakac** [comment]
I am experiencing exactly same issue. In-app messaging test message is displayed on iOS but not on Android. I can see in Logcat that the In-app messaging module was successfully started, but when I try to use the instance id to send a test message nothing shows up. It seems like that for some reason my device (android emulator) is not marked as testing device:
`I/FIAM.Headless: Forcing fetch from service rather than cache. Test Device: false`

This happens in an app that I am working on. When I try to setup a new app and connect in app messaging everything works as expected and Logcat shows:
`I/FIAM.Headless: Forcing fetch from service rather than cache. Test Device: true`

I already tried re-downloading google-services.json.

Any idea what could cause a device not being marked as testing device? It's not an instance id issue: I double checked and instance id is correct. Also, I am not sure if it's relevant, but I am using also other firebase services in my application and everything else works.

**Comment by jkblgithub** [comment]
> Could you try re-downloading the google-services.json file?

Hi, I downloaded the services file again, installed it, did a clean and a rebuild and got the new instance id. Unfortunately the same issue persists.

**Comment by aguatno** [comment]
Hi @jkblgithub This seems to be a bit tricky, would it be possible for you to obtain a full stack trace? What device model are you using?

**Comment by jkblgithub** [comment]
Hi,

Yes I can get a stack trace - is there a debug param that needs to be set as I did not notice anything in the normal stack besides what I posted above. Using a Galaxy J5 Prime, but can also run on an Emulator if necessary.

**Comment by aguatno** [comment]
Hi @jkblgithub just paste here the logcat  when the device thows this error message.

**Comment by jkblgithub** [comment]
I attach a summary of the Firebase logs and then the full log. Package Id has been removed.

[FBSummary.txt](https://github.com/firebase/firebase-android-sdk/files/4197623/FBSummary.txt)
[AllLogs.txt](https://github.com/firebase/firebase-android-sdk/files/4197624/AllLogs.txt)

**Comment by aguatno** [comment]
Thanks for the logs. Let me take a look.

**Comment by aguatno** [comment]
@jkblgithub Things are working fine on my end. Were you be able to reproduce using different device or Android Emulator? Is there any particular pattern you notice (device model, Android API versions) that significantly contributes to the issue?

**Comment by jkblgithub** [comment]
You can close this ticket as I see that it will not be resolved.

**Comment by samtstern** [comment]
@JasonAHeron do you know what can cause this log?
```
W/FIAM.Headless: Service fetch error: INVALID_ARGUMENT: Request contains an invalid argument.
```

**Comment by BakhtarSobat** [comment]
Update the dependency. After updating it worked for.

If you are using gRPC in your project, make sure you don't exclude the modules.

**Comment by JasonAHeron** [comment]
This should now be fixed with the latest version of our SDK!
