### ISSUE TITLE
Firebase Performance Monitoring fails to instrument network traces

### ISSUE THREAD

**Issue by satyarths** [firebase/firebase-android-sdk#2457]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Performance-Monitoring (Database, Firestore, Storage, Functions, etc)
  * Component version:  	19.1.1

### [REQUIRED] Step 3: Describe the problem

While insturmenting with firebase performance to enable HTTP traces (https://firebase.google.com/docs/perf-mon/get-started-android#add-perfmon-plugin). I get the following error message
```
Can't instrument because of null. Copying as is.
```

#### Steps to reproduce:

This happens when running any :app:assembleDebug

#### Relevant Code:

// TODO(you): code here to reproduce the problem
```

**Comment by satyarths** [comment]
So turns out the issue was the version of "asm" used..My build classpath dependencies included asm:7.0 while from https://github.com/firebase/firebase-android-sdk/issues/1556 I understand perf-monitoring requires 9.0 . 

This re-enables firebase tracing for me.  However I see new errors(warnings ?) while running the build.

```
java.lang.ClassNotFoundException: org.apache.http.impl.client.DefaultHttpClient
java.lang.ClassNotFoundException: io.jsonwebtoken.Jwt
java.lang.ClassNotFoundException: io.jsonwebtoken.Claims
```

Can you let me know if these are of consequence.

**Comment by jposuna** [comment]
Hi @satyarths , thank you for reporting this. To be able to debug further, could you provide the following:

1. What version of perf-plugin are you using?
2. The results of running `./gradlew app:dependencies` so that we can look at the resolved dependencies versions
3. The complete stack trace. It will help us debug, and also see whether this is happening for many/all classes, or only a few.
4. If possible, can you provide us with a sample app where this issue is reproducible?

**Comment by satyarths** [comment]
1. I'm running 1.3.4
2. I have mentioned the failing dependency issue above. My dependencies were resolving to asm:7.0, while firebase perf requires asm:9.0 . 
3.The complete stacktraceonly includes 10k lines of "Can't instrument because of null. Copying as is."
4. Considering the issue is resolved we can mark this as closed.


Although I'd recommend providing a better error message apart from the above..It took me a long time to figure out exactly what is the issue here.

**Comment by jposuna** [comment]
Thank you @satyarths , we will look into how we can provide a more meaningful error message.

Regarding the issue, I understood from your second message that the issue wasn't resolved and you were still facing some issue. The questions I was asking for were to debug the issue with:
```
java.lang.ClassNotFoundException: org.apache.http.impl.client.DefaultHttpClient
java.lang.ClassNotFoundException: io.jsonwebtoken.Jwt
java.lang.ClassNotFoundException: io.jsonwebtoken.Claims
```

If you are still facing this issue, could you provide the information for the issue? If it's all solved, please feel free to close the issue.

**Comment by satyarths** [comment]
Hi @jposuna,
Sorry I missed that. I am still facing this issue. However I do not have  the time right now to create a repro for this. I'll close the issue  the and reopen when I can  provide the repro. Thank you very much  for  helping me with this.
