### ISSUE TITLE
google-services:4.3.9 breaks firebase

### ISSUE THREAD

**Issue by ColtonIdle** [firebase/firebase-android-sdk#2894]
Android app

My root build.gradle.kts contains

```
    dependencies {
        classpath("com.google.gms:google-services:4.3.8")
```

I updated today com.google.gms:google-services:4.3.8 to com.google.gms:google-services:4.3.9 and my android app crashes on launch now due to firebase.

```
2021-08-06 22:30:10.671 13469-13469/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rollertoaster.app.free, PID: 13469
    java.lang.RuntimeException: Unable to resume activity {com.rollertoaster.app.free/com.rollertoaster.app.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.rollertoaster.app.free. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.rollertoaster.app.free. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
        at com.google.firebase.perf.FirebasePerformance.getInstance(FirebasePerformance.java:132)
        at com.google.firebase.perf.FirebasePerformanceInitializer.onAppColdStart(FirebasePerformanceInitializer.java:29)
        at com.google.firebase.perf.application.AppStateMonitor.sendAppColdStartUpdate(AppStateMonitor.java:274)
        at com.google.firebase.perf.application.AppStateMonitor.onActivityResumed(AppStateMonitor.java:195)
        at android.app.Application.dispatchActivityResumed(Application.java:436)
        at android.app.Activity.dispatchActivityResumed(Activity.java:1265)
        at android.app.Activity.onResume(Activity.java:1789)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

If I revert back from .9 to .8, then everything works again.

Not sure if it's a firebase issue or a google-services issue, but I figured I'd be proactive.

**Comment by Vivecstel** [comment]
Same here. Reverted back to previous version.

**Comment by DDR13GIT** [comment]
I lost precious 6 hours of my life for this problem -.-
reverted back to .8

**Comment by juanlabrador** [comment]
Last night I didn't understand what happened, until compare with another project.

**Comment by carlonzo** [comment]
for what I can see in my project, the plugin does not generate the resources in the `app/build/generated/res/google-services/<buildtype>/values/values.xml` file required by the SDK out of the `google-services.json`

**Comment by Dta-KO** [comment]
same error! what is solution ?

**Comment by aguatno** [comment]
It looks like the 4.3.9 is having multiple issues. The [official docs ](https://developers.google.com/android/guides/google-services-plugin)still say 4.3.8, so I'd suggest reverting back to .8 at-least for now.

**Comment by Naveen3Singh** [comment]
Got the same problem today after updating google-services to 4.3.9. Reverting to 4.3.8 fixes the initialization.

`W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
`

**Comment by inv-jithin** [comment]
Got the same error. Is there any solution for this

**Comment by davidmotson** [comment]
A fix is on the way and will be deployed as 4.3.10, for now use 4.3.9

**Comment by davidmotson** [comment]
google-services-plugin 4.3.10 is now live and should fix the above issue, please re-open if this is not the case.

**Comment by ColtonIdle** [comment]
Confirmed. Fixed for me. Thank you for the quick turnaround.

**Comment by pocketutilities** [comment]
Damn I have been trying to figure out what am I doing wrong and now here I am finding this :)

**Comment by kartikj07** [comment]
I could generate the values.xml on 4.3.8 and as soon as I update it to 4.3.10 the file doesn't get generated. I tried to clean/rebuild and invalidate caches and restart, but I still cannot generate the values.xml file. I am using `OneSignal 4.5.1`, `Firebase BOM 28.4.0`, and `Gradle plugin 4.2.2`. Please help me resolve the issue.
