### ISSUE TITLE
[Dynamic Links] Android Chrome users always redirected to Play Store in browser even with app installed

### ISSUE THREAD

**Issue by lucaventura** [firebase/firebase-android-sdk#4884]
EDIT: See comments. This appears to be an underlying bug in the latest Chrome Android app (112 (112.0.5615.47/.48). Bug report [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1433137).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1
  * Firebase Component: Dynamic Links (Database, Firestore, Storage, Functions, etc)
  * Component version: 26.1.1

#### Steps to reproduce:

After updating `targetSdkVersion` from `31` to `33` users on Android 13 are always redirected to the Play Store when clicking a dynamic link even if the app is installed.

I have verified the `assetlinks.json` is correctly hosted and there are no errors shown in the "Deep Links" section of the Google Play Store developer console.

#### Relevant Code:

```
<intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="ourdomain.com"
                    android:scheme="http" />

                <data
                    android:host="ourdomain.com"
                    android:scheme="https" />

                <data
                    android:host="ourdomain.page.link"
                    android:scheme="https" />
                <data
                    android:host="ourdomain.page.link"
                    android:scheme="http" />
            </intent-filter>


```

**Comment by Bylynka** [comment]
I have the same issue. I also have verified assetlinks.json. On Android 11 everything works as expected, on Android 13 user is always redirected to PlayStore.

**Comment by lucaventura** [comment]
> Also, I can reproduce the issue only in web browsers. If I try to open a dynamic link from WhatsApp it works as expected. I was able to reproduce the issue in Firefox. But Firefox has 'Open links in apps' setting, after I enabled it dynamic links started to work in Firefox.

Yes we have the same thing happening, it's the strangest thing... if we paste the link into notes/messages and click it the link works fine, but if we click the link through Chrome on a device (e.g from a link embedded in a web page), the issue happens.

**Comment by lucaventura** [comment]
@argzdev I saw that issue, which is why I added another `<data>` tag in the Intent Filter for the domain of the actual deep link (seen in my original code snippet above) but that did not resolve the issue. I verified both the `ourdomain.page.link` and `ourdomain.com` are whitelisted in the Firebase Console.

**Comment by argzdev** [comment]
Thanks for verifying, @lucaventura. I've noticed that you're using an old version of our SDK. Your current Firebase BoM version maps to Dynamic links version `19.1.1`, the latest version as of the moment is `21.1.0`. Could you try using the latest version of BoM `31.4.0` and see if that works? We usually suggest this to avoid issues that may have been fixed in the most recent versions. Thanks!

**Comment by lucaventura** [comment]
@argzdev Thanks I'll try that and let you know. One interesting thing is if we try to replicate this on a fresh install of our app on an Android 13 device, it works fine, but we have users in production also running Android 13 that face the issue with being redirected to the Play Store in their browser. We verified with a few of them that the "Open supported links" setting was still toggled on in our app settings on their device.

**Comment by lucaventura** [comment]
@argzdev After updating to the latest BoM and pushing our app to a few testers that are experiencing the issue, it did not resolve the problem. We are not able to replicate the issue on a fresh install, but it seems for users who previously had the older version installed and then updated to the newest version they still experience the issue of being redirected to the Play Store in their mobile browser.

This is only happening if the dynamic link is clicked in a mobile web browser. If you copy the same link, paste it into notes/messages, then click it from there the link works perfectly fine and opens the app.

Another strange behavior that we've found is, if you click the deep link from an incognito Chrome window, you are prompted to either "Stay" or "Leave" incognito mode - if you click "Stay" it redirects to the Play Store in a Chrome window. If you click "Leave", it will properly open the app.

**Comment by lucaventura** [comment]
@argzdev Ok I was able to pinpoint this issue to the latest Chrome Android app (112 (112.0.5615.47/.48). The Android 13 device we were testing with that didn't have the issue was on an older Chrome version, as soon as we updated to the latest Chrome app and re-tested by clicking the deep link in chrome the issue started happening (being redirected to Google Play in the browser).

**Comment by argzdev** [comment]
Nice catch, @lucaventura! This is an impressive investigation. I tested this initially with Chrome app version `101.0.4951.74` and it was working fine. After updating Chrome to version `112.0.5615.48`, testing the same dynamic link redirects me to the Google Play URL in the browser. That said, since we've confirmed that this issue is on Chrome side, we can keep this thread open for tracking until they're able to resolve the issue on their side.

**Comment by lucaventura** [comment]
Worth also noting this is happening regardless of Android version. It just so happens that this issue coincided with an internal release for our team updating our sdk target from `31` to `33`, hence the initial suspicion that this was isolated to Android 13, but it's not. Gained a few more grey hairs because of this one.

**Comment by argzdev** [comment]
I was wondering about that too. Really appreciate the updates, @lucaventura.

**Comment by argzdev** [comment]
Closing this issue since this has been fixed on Chrome side.
