### ISSUE TITLE
The following Android dependencies are set to compileOnly which is not supported: com.google.j2objc:j2objc-annotations:2.8

### ISSUE THREAD

**Issue by ShivamGoyal1899** [firebase/firebase-android-sdk#6232]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Ladybug 2024.2.1 Canary 9
  * Firebase Component: BOM
  * Component version: 33.2.0

#### Steps to reproduce:

- Upgrade BOM to 33.2.0 from 33.1.2.
- Build will fail saying
```
The following Android dependencies are set to compileOnly which is not supported:
  -> com.google.j2objc:j2objc-annotations:2.8
```

#### Relevant Code:

No code change

**Comment by ShivamGoyal1899** [comment]
we faced a very similar issue w/ `androidx.media3` several weeks back. https://github.com/androidx/media/issues/1325

**Comment by lehcar09** [comment]
Hi @ShivamGoyal1899, thank you for reaching out. I'm not familiar with the `j2objc-annotations` dependency. Per checking,
 Firebase Android SDK does not use the dependency `j2objc-annotations`. 

This issue means that the Gradle build system used by Android cannot determine how to handle the annotations provided by the j2objc-annotations library within an Android project. If you're not using the latest Android Gradle plugin, I would suggest try using the latest version to see if the issue is already resolved. 

To get better help, It would be best to reach out to the [j2objc support team](https://developers.google.com/j2objc/contact). That said, I'll be closing this issue now. Let me know if you have questions or clarifications. Thanks!

**Comment by ShivamGoyal1899** [comment]
@lehcar09 we are on latest AGP and Gradle. also the issue does not comes up while using BOM v33.1.2. it fails to compile after bumping BOM to v 33.2.0 (no other code change).

**Comment by ShivamGoyal1899** [comment]
@lehcar09 this is still not working on latest BOM. can you please take a look?

**Comment by cpovirk** [comment]
Someone reported this to us on the Guava side in https://github.com/google/guava/issues/7397. I'm working to fix it there. Once I do so, Firebase should be able to upgrade to a new version of Guava, and the problem should go away. Sorry for the trouble.

**Comment by cpovirk** [comment]
I released [Guava 33.3.1](https://github.com/google/guava/releases/tag/v33.3.1), which contains what I believe should be a fix. Is expect that users could eliminate the error by declaring an explicit dependency on that version, and Firebase can upgrade to that version so that anyone who then upgrades Firebase will likewise no longer see the problem. Let me know if any of that doesn't work as expected. Sorry again for the problem.

**Comment by ShivamGoyal1899** [comment]
@lehcar09 can you please bump and confirm?

**Comment by lehcar09** [comment]
Thank you for sharing the insight and fix @cpovirk. 

Hi @ShivamGoyal1899, I tried reproducing the issue using the Firebase BOM 33.2.0, however, I did not encounter the issue. 

Can you help and see what I'm missing here?

build.gradle.kts
```
plugins {
    id("com.android.application") version "8.6.1" apply false
    id("com.android.library") version "8.6.1" apply false
    id("org.jetbrains.kotlin.android") version "2.0.10" apply false
    id("com.google.gms.google-services") version "4.4.2" apply false
}
```

app/build.gradle.kts
```
    implementation(platform("com.google.firebase:firebase-bom:33.2.0"))
    implementation("com.google.firebase:firebase-analytics")
```

Alternatively, you can try adding the new Guava dependency explicitly in your app/gradle file to override the current version. Upon Checking the Google Analytics 22.1.0 is using `com.google.guava:guava:31.1-android`.

```
dependencies {
  implementation("com.google.guava:guava:33.3.1-android")
}
```

**Comment by ShivamGoyal1899** [comment]
@lehcar09 we currently use all below attached dependencies in our project.

<img width="430" alt="Screenshot 2024-10-01 at 11 56 57 AM" src="https://github.com/user-attachments/assets/a292c2fd-62b1-4e25-b19f-886014c6832e">

**Comment by ShivamGoyal1899** [comment]
@lehcar09 also, media3 folks did bump to new guava versions and were able to resolve the issue. https://github.com/androidx/media/issues/1700

**Comment by lehcar09** [comment]
Thank you for additional details you shared. I'm still having trouble issue in reproducing the issue. However, I'll notify our engineers about this to bump the Guava version in our SDK.

Just to note, we cannot provide any timeline on this. As a workaround for now, you can try adding the new Guava 33.3.0 dependency explicitly in your app/gradle file to override the current version.

**Comment by ShivamGoyal1899** [comment]
understood.

**Comment by farimarwat** [comment]
add this in app's level gradle and will be fixed:
```
/*
        Added below dependency to avoid this:
        The following Android dependencies are set to compileOnly which is not supported:
        -> com.google.j2objc:j2objc-annotations:2.8
         */
        implementation("com.google.j2objc:j2objc-annotations:2.8")
```

**Comment by shyvum** [comment]
@lehcar09 any guesses if this is bumped?
