### ISSUE TITLE
Internal error in Cloud Firestore (26.0.0)

### ISSUE THREAD

**Issue by Kim-DongGeun** [firebase/firebase-android-sdk#7319]
- Android Studio version: Android Studio Narwhal Feature Drop | 2025.1.2 Patch  1
- Firebase Component: firestore
- Component version: 26.0.0

#### Steps to reproduce:

After upgrading to firestore 26.0.0, our application is experiencing some crashes on Samsung devices
and we use DataStore version 1.1.7 

#### Stack trace

```
Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (26.0.0).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:546)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
       
Caused by androidx.datastore.core.CorruptionException: Unable to parse preferences proto.
       at androidx.datastore.preferences.PreferencesMapCompat$Companion.readFrom(PreferencesMapCompat.kt:34)
       at androidx.datastore.preferences.core.PreferencesFileSerializer.readFrom(PreferencesFileSerializer.jvmAndroid.kt:46)
       at androidx.datastore.core.FileReadScope.readData$suspendImpl(FileStorage.kt:169)
       at androidx.datastore.core.FileReadScope.readData(FileStorage.kt)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invokeSuspend(StorageConnection.kt:74)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:1)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:2)
       at androidx.datastore.core.FileStorageConnection.readScope(FileStorage.kt:101)
       at androidx.datastore.core.StorageConnectionKt.readData(StorageConnection.kt:74)
       at androidx.datastore.core.DataStoreImpl.readDataFromFileOrDefault(DataStoreImpl.kt:323)
       at androidx.datastore.core.DataStoreImpl.readDataOrHandleCorruption(DataStoreImpl.kt:365)
       at androidx.datastore.core.DataStoreImpl.access$getStorageConnectionDelegate$p(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl.access$readDataOrHandleCorruption(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invokeSuspend(DataStoreImpl.kt:437)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:2)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:1)
       at androidx.datastore.core.SingleProcessCoordinator.lock(SingleProcessCoordinator.kt:41)
       at androidx.datastore.core.DataStoreImpl$InitDataStore.doRun(DataStoreImpl.kt:434)
       at androidx.datastore.core.RunOnce.runIfNeeded(DataStoreImpl.kt:497)
       at androidx.datastore.core.DataStoreImpl.readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt:266)
       at androidx.datastore.core.DataStoreImpl.access$getStorageConnectionDelegate$p(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl.access$readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl$readState$2.invokeSuspend(DataStoreImpl.kt:218)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
       
Caused by androidx.datastore.preferences.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
       at androidx.datastore.preferences.protobuf.UnknownFieldSchema.mergeOneFieldFrom(UnknownFieldSchema.java:98)
       at androidx.datastore.preferences.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3009)
       at androidx.datastore.preferences.protobuf.MessageSchema.mergeFrom(MessageSchema.java:2955)
       at androidx.datastore.preferences.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1599)
       at androidx.datastore.preferences.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1742)
       at androidx.datastore.preferences.PreferencesProto$PreferenceMap.parseFrom(PreferencesProto.java:198)
       at androidx.datastore.preferences.PreferencesMapCompat$Companion.readFrom(PreferencesMapCompat.kt:32)
       at androidx.datastore.preferences.core.PreferencesFileSerializer.readFrom(PreferencesFileSerializer.jvmAndroid.kt:46)
       at androidx.datastore.core.FileReadScope.readData$suspendImpl(FileStorage.kt:169)
       at androidx.datastore.core.FileReadScope.readData(FileStorage.kt)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invokeSuspend(StorageConnection.kt:74)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:1)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:2)
       at androidx.datastore.core.FileStorageConnection.readScope(FileStorage.kt:101)
       at androidx.datastore.core.StorageConnectionKt.readData(StorageConnection.kt:74)
       at androidx.datastore.core.DataStoreImpl.readDataFromFileOrDefault(DataStoreImpl.kt:323)
       at androidx.datastore.core.DataStoreImpl.readDataOrHandleCorruption(DataStoreImpl.kt:365)
       at androidx.datastore.core.DataStoreImpl.access$getStorageConnectionDelegate$p(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl.access$readDataOrHandleCorruption(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invokeSuspend(DataStoreImpl.kt:437)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:2)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:1)
       at androidx.datastore.core.SingleProcessCoordinator.lock(SingleProcessCoordinator.kt:41)
       at androidx.datastore.core.DataStoreImpl$InitDataStore.doRun(DataStoreImpl.kt:434)
       at androidx.datastore.core.RunOnce.runIfNeeded(DataStoreImpl.kt:497)
       at androidx.datastore.core.DataStoreImpl.readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt:266)
       at androidx.datastore.core.DataStoreImpl.access$getStorageConnectionDelegate$p(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl.access$readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt)
       at androidx.datastore.core.DataStoreImpl$readState$2.invokeSuspend(DataStoreImpl.kt:218)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
```

**Comment by mathieuedet** [comment]
Hi,
@dconeybe, on this [this comment](https://github.com/firebase/firebase-android-sdk/issues/7286#issuecomment-3225667719), you have recommended to do use 1.1.7 datastore version. Do you think that the issue is related to that ?

**Comment by rohansohonee1** [comment]
I think we are also facing a similar issue using Flutterfire. Please check.
```
firebase_core v4.0.0
cloud_firestore v6.0.0
```

[com.agendaboa.app_issue_4b3b206dbc309d32c74cf587971590e6_crash_session_68B6D51C021D0001360121354AB04863_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/22093282/com.agendaboa.app_issue_4b3b206dbc309d32c74cf587971590e6_crash_session_68B6D51C021D0001360121354AB04863_DNE_0_v2_stacktrace.txt)

**Comment by dconeybe** [comment]
> on this [this comment](https://github.com/firebase/firebase-android-sdk/issues/7286#issuecomment-3225667719), you have recommended to do use 1.1.7 datastore version. Do you think that the issue is related to that ?

Yes, this looks like exactly the same issue as #7286 and force-upgrading the `androidx.datastore:datastore-preferences` dependency as suggested in https://github.com/firebase/firebase-android-sdk/issues/7286#issuecomment-3225667719 should fix it. Thanks for pointing this out, @mathieuedet.

**Comment by Kim-DongGeun** [comment]
@dconeybe 
Thanks for the quick reply
I already read the issue [#7286 ](https://github.com/firebase/firebase-android-sdk/issues/7286) and
we are using datastore 1.1.7 and this is happening despite the fact that we are using datastore 1.1.7
And looking at the stacktrace, it is slightly different from the issue you referenced, so I think it is a different issue

**Comment by mathieuedet** [comment]
@Kim-DongGeun , if you try command of [this post](https://github.com/firebase/firebase-android-sdk/issues/7286#issuecomment-3225667719), you have the right result as described ?

Else, @dconeybe issue should be opened again if datastore upgrade to 1.1.7 doesn't fix that ?

**Comment by Kim-DongGeun** [comment]
@mathieuedet 

This is the result of running the command in [this post](https://github.com/firebase/firebase-android-sdk/issues/7286#issuecomment-3225667719)
I think I have version 1.1.7 of datastore applied, but it still occurs crashes

```
./gradlew :***:dependencies 2>&1 | grep datastore-preferences: | sed -e 's/|\|\s\+\|+\|\\//g' | sort | uniq
+--- androidx.datastore:datastore-preferences:1.1.7
+--- androidx.datastore:datastore-preferences:1.1.7 (*)
+--- androidx.datastore:datastore-preferences:1.1.7 (n)
+--- androidx.datastore:datastore-preferences:{strictly 1.1.7} -> 1.1.7 (c)
|         |         +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|         |         \--- androidx.datastore:datastore-preferences:1.1.7 (c)
|         |         |         +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    +--- androidx.datastore:datastore-preferences:1.1.7 (*)
|    |    +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    |    \--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    |    |    +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    |    |    |    |    +--- androidx.datastore:datastore-preferences:1.1.3 -> 1.1.7
|    |    |    |    |    |         |         +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    |    |    |    |    |         |         |         +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    |    |    |    |    |         |         |    +--- androidx.datastore:datastore-preferences:1.1.7 (c)
|    |    |    |    |    |         |         |    |    +--- androidx.datastore:datastore-preferences:1.1.7 (c)
```

**Comment by dconeybe** [comment]
@Kim-DongGeun That gradle output you provided indeed confirms that you are using a version of `androidx.datastore:datastore-preferences` with the fix (v1.1.7).

The other piece of the fix is the "corruption handler" added by the firebase-android-sdk in https://github.com/firebase/firebase-android-sdk/pull/7277. This fix will be included in the next release of the firebase-android-sdk. This next release is planned to be 2-3 weeks from now, in mid-late September 2025.

If you don't want to wait until that release then I can give you instructions to compile the firebase-android-sdk yourself and link it into your app. Doing so would at least confirm that the purported fix actually fixes the issue you are experiencing. Please reply back if you'd like to try this out.

**Comment by Kim-DongGeun** [comment]
@dconeybe 
Thank you for reply
I'll wait next release
