### ISSUE TITLE
Your client does not have permission to get URL /identitytoolkit/v3/relyingparty/signupNewUser from this server

### ISSUE THREAD

**Issue by thanhhai08sk** [firebase/firebase-android-sdk#942]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: IntelliJ IDEA 2019.2 (Community Edition) Build #IC-192.5728.98, built on July 23, 2019
  * Firebase Component: Authentication
  * Component version: com.google.firebase:firebase-auth:19.1.0

### [REQUIRED] Step 3: Describe the problem
Just updated from firebase-auth:16.1.0. The app has about 300 downloads daily, in the last 5 days I got 75 crashes affecting 45 users when signing up with Google Account. No problem when I test on my device/emulator.

#### Steps to reproduce:

Stacktrace:
`
com.google.firebase.FirebaseException: An internal error has occurred. [ <!DOCTYPE html> <html lang=en>   <meta charset=utf-8>   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">   <title>Error 403 (Forbidden)!!1</title>   <style>     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}   </style>   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>   <p><b>403.</b> <ins>That’s an error.</ins>   <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/signupNewUser</code> from this server.  <ins>That’s all we know.</ins> ] at com.google.firebase.auth.api.internal.zzdx.zza(com.google.firebase:firebase-auth@@19.1.0:18) at com.google.firebase.auth.api.internal.zzfa.zza(com.google.firebase:firebase-auth@@19.1.0:21) at com.google.firebase.auth.api.internal.zzet.zza(com.google.firebase:firebase-auth@@19.1.0:34) at com.google.firebase.auth.api.internal.zzev.zza(com.google.firebase:firebase-auth@@19.1.0:74) at com.google.firebase.auth.api.internal.zzed.zza(com.google.firebase:firebase-auth@@19.1.0:18) at com.google.android.gms.internal.firebase_auth.zza.onTransact(com.google.firebase:firebase-auth@@19.1.0:13) at android.os.Binder.execTransact(Binder.java:453)
`

#### Relevant Code:

```
    override fun logIn(): Single<LogInResult> =
            getGoogleAccount(signInClient)
                    .toOptionalSingle()
                    .flatMap { accountOptional ->
                        when (val account = accountOptional.toNullable()) {
                            null -> singleJust(LogInResult.Canceled)
                            else -> Single.create<LogInResult> { emitter ->
                                FirebaseAuth
                                        .getInstance()
                                        .signInWithCredential(account.getCredential())
                                        .addOnCompleteListener { task: Task<AuthResult> ->
                                            if (task.isSuccessful)
                                                emitter.onSuccess(LogInResult.Success(task.result!!.toFirebaseUser()))
                                            else
                                                emitter.onError(task.exception!!)
                                        }
                            }
                        }
                    }

    private fun GoogleSignInAccount.getCredential(): AuthCredential =
            GoogleAuthProvider
                    .getCredential(this.idToken, null)
```

**Comment by artsemionov** [comment]
Same here https://github.com/firebase/firebase-android-sdk/issues/944

**Comment by thanhhai08sk** [comment]
The error is still there but the stacktrace is changed to 
`AuthError.Failure: Firebase.FirebaseException: An internal error has occurred. [ 7: ]`
Similar to #474

**Comment by artsemionov** [comment]
Try it guys, it just helped me: https://medium.com/@chonnaronghanyawongse/coding-diary-why-my-firestore-doesnt-work-2db41fb82121

**Comment by artsemionov** [comment]
Nvm. It did not.

**Comment by artsemionov** [comment]
@thanhhai08sk did you have this exception on the 16.1.0 version? I'm thinking about just downgrading the version instead of waiting a miracle from Google team.

**Comment by thanhhai08sk** [comment]
> @thanhhai08sk did you have this exception on the 16.1.0 version? I'm thinking about just downgrading the version instead of waiting a miracle from Google team.

It was 16.1.0 for many months, didn't notice any similar issue.

**Comment by aguatno** [comment]
Hi @thanhhai08sk sorry for the delay. Based on the error logs, I could say that this might be related to #944. There was an initial finding that this could be a network issue. I created a bug (b/144577889) internally, and progress updates will be posted here as well. Thanks.

**Comment by aguatno** [comment]
Hi @thanhhai08sk The issue has been fixed and indentified. The fix compose of better error handling that deals with network exceptions. However, I may not be able provide you with any specifics as to when will the fix be released in production. For now, try to catch the issue manually. Once the fix goes live, you'll not need to update to the new SDK version.

I'll close this when the fix is in prod.

**Comment by thanhhai08sk** [comment]
> Hi @thanhhai08sk The issue has been fixed and indentified. The fix compose of better error handling that deals with network exceptions. However, I may not be able provide you with any specifics as to when will the fix be released in production. For now, try to catch the issue manually. Once the fix goes live, you'll not need to update to the new SDK version.
> 
> I'll close this when the fix is in prod.

Glad to here it. Thanks for the fix!

**Comment by manelizzard** [comment]
Suffering same issue here. Waiting for the release to become live.

Thanks!

**Comment by aguatno** [comment]
Thanks for patiently waiting. I got confirmation from our engineering team that this issue has been fixed externally. They just need to be using the newest release of Google Play services. SDK upgrade will not be needed. 

Closing this issue, please let us know if it's still happening and we can re-open it.

**Comment by thanhhai08sk** [comment]
@aguatno I'm still experiencing issues with login
`
com.google.firebase.FirebaseException: An internal error has occurred. [ <!DOCTYPE html> <html lang=en>   <meta charset=utf-8>   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">   <title>Error 403 (Forbidden)!!1</title>   <style>     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}   </style>   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>   <p><b>403.</b> <ins>That’s an error.</ins>   <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/verifyAssertion</code> from this server.  <ins>That’s all we know.</ins> ]  stackTrace = com.google.firebase.FirebaseException: An internal error has occurred. [ <!DOCTYPE html> <html lang=en>   <meta charset=utf-8>   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">   <title>Error 403 (Forbidden)!!1</title>   <style>     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}   </style>   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>   <p><b>403.</b> <ins>That’s an error.</ins>   <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/verifyAssertion</code> from this server.  <ins>That’s all we know.</ins> ] at com.google.firebase.auth.api.internal.zzdv.zza(com.google.firebase:firebase-auth@@19.2.0:18) at com.google.firebase.auth.api.internal.zzfc.zza(com.google.firebase:firebase-auth@@19.2.0:21) at com.google.firebase.auth.api.internal.zzes.zza(com.google.firebase:firebase-auth@@19.2.0:34) at com.google.firebase.auth.api.internal.zzeu.zza(com.google.firebase:firebase-auth@@19.2.0:74) at com.google.firebase.auth.api.internal.zzeb.zza(com.google.firebase:firebase-auth@@19.2.0:18) at com.google.android.gms.internal.firebase_auth.zza.onTransact(com.google.firebase:firebase-auth@@19.2.0:13) at android.os.Binder.execTransact(Binder.java:739)
`
It got 140 reports on Crashlytics, affecting 40 users in 7 days.
The URL is different than the last time `identitytoolkit/v3/relyingparty/verifyAssertion`, but my code is still the same.
